version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # These are for React hot-reloading to work correctly inside Docker
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/game.db
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=1883
    depends_on:
      - mqtt

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - '1883:1883' # Standard MQTT port
      - '9001:9001' # MQTT over WebSockets for the frontend
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log 